server:
  port: 1299
zuul:
  prefix: /services
  ignored-services: '*'
  routes:
    system:
      path: /system/**
      service-id: system-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #服务注册的地址
  instance:
    instance-id: zuul-server:1299
    prefer-ip-address: true

spring:
  application:
    name: zuul-server
