server:
  port: 9696

spring:
  application:
      name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/solargen/hrm-config-1229.git #仓库的地址
          searchPaths: src/main/resources #仓库的子目录中寻找配置文件

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #服务注册的地址
  instance:
    instance-id: config-server:9696
    prefer-ip-address: true

